name: Android CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Java
        run: java -version

      - name: Cache Gradle
        uses: actions/cache@v4

        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      - name: Give Execute Permission
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4

        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk


        
