name: Android CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Java
        run: java -version

      - name: Show Project Files
        run: ls

      - name: Give Permission
        run: chmod +x gradlew
        
